#!/usr/bin/env python3
"""
Regenerate docker-compose.override.yml and Caddyfile from ./clients/*.env.

The client files in ./clients/ are the single source of truth. Each file is
named <client>.env and must contain at least a DOMAIN=... line (plus the app
secrets). Run this after adding or editing a client, then:

    docker compose up -d

add-client.sh / remove-client.sh call this for you, so you rarely run it by hand.
"""
import os
import glob
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CLIENTS_DIR = os.path.join(HERE, "clients")

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,30}$")


def read_env(path):
    data = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            data[k.strip()] = v.strip()
    return data


def load_clients():
    clients = []
    for path in sorted(glob.glob(os.path.join(CLIENTS_DIR, "*.env"))):
        name = os.path.splitext(os.path.basename(path))[0]
        if not NAME_RE.match(name):
            raise SystemExit(f"Invalid client name '{name}' (use lowercase letters, digits, dashes).")
        env = read_env(path)
        domain = env.get("DOMAIN", "").strip()
        if not domain:
            raise SystemExit(f"clients/{name}.env is missing a DOMAIN= line.")
        clients.append({"name": name, "domain": domain})
    return clients


def render_compose(clients):
    lines = [
        "# GENERATED by generate.py — do not edit by hand.",
        "# Add/remove clients with add-client.sh / remove-client.sh.",
        "name: coop",
        "services:",
    ]
    for c in clients:
        n = c["name"]
        lines += [
            f"  app-{n}:",
            "    build:",
            "      context: ../..",
            "      dockerfile: deploy/vps/Dockerfile",
            "    image: coop-app:latest",
            "    restart: unless-stopped",
            "    env_file:",
            f"      - ./clients/{n}.env",
            "    environment:",
            f"      DATABASE_URL: postgresql://postgres:${{POSTGRES_PASSWORD}}@postgres:5432/coop_{n}",
            # Shared token so HQ can read member counts and set access on every
            # tenant. Comes from deploy/vps/.env, so all clients get it centrally.
            "      HQ_SYNC_TOKEN: ${HQ_SYNC_TOKEN:-}",
            "    volumes:",
            # Persist uploaded files (member photos, payout evidence) across
            # rebuilds. One volume per client so societies stay isolated.
            f"      - uploads-{n}:/app/static/uploads",
            "    depends_on:",
            "      postgres:",
            "        condition: service_healthy",
            "",
        ]
    if clients:
        lines.append("volumes:")
        for c in clients:
            lines.append(f"  uploads-{c['name']}:")
        lines.append("")
    return "\n".join(lines) + "\n"


def landing_domain():
    """The product's marketing domain to serve the static landing page at, or ''.

    Read from ./.landing-domain (server-local, gitignored) so the tooling stays
    generic. Example file contents: cooperativems.com
    """
    path = os.path.join(HERE, ".landing-domain")
    if os.path.exists(path):
        return open(path, encoding="utf-8").read().strip()
    return ""


def landing_api_client(clients):
    """Return the client app that should receive public marketing leads."""
    path = os.path.join(HERE, ".landing-api-client")
    configured = ""
    if os.path.exists(path):
        configured = open(path, encoding="utf-8").read().strip()
    names = {c["name"] for c in clients}
    if configured and configured in names:
        return configured
    if "hq" in names:
        return "hq"
    return clients[0]["name"] if clients else ""


def render_caddyfile(clients):
    lines = ["# GENERATED by generate.py — do not edit by hand.", ""]
    landing = landing_domain()
    if landing:
        # Serve the static marketing landing page at the apex (+ www).
        hosts = landing if landing.startswith("www.") else f"{landing}, www.{landing}"
        api_client = landing_api_client(clients)
        lines += [
            f"{hosts} {{",
        ]
        if api_client:
            lines += [
                "    @marketing_api path /api/marketing/*",
                f"    reverse_proxy @marketing_api app-{api_client}:8000",
            ]
        lines += [
            "    root * /srv/landing",
            "    encode gzip",
            "    file_server",
            "}",
            "",
        ]
    if not clients and not landing:
        # Caddy needs at least one site block to start cleanly.
        lines += [":80 {", "    respond \"No clients configured yet.\" 200", "}", ""]
    for c in clients:
        lines += [
            f"{c['domain']} {{",
            f"    reverse_proxy app-{c['name']}:8000",
            "}",
            "",
        ]
    return "\n".join(lines) + "\n"


def main():
    clients = load_clients()
    with open(os.path.join(HERE, "docker-compose.override.yml"), "w", encoding="utf-8") as f:
        f.write(render_compose(clients))
    with open(os.path.join(HERE, "Caddyfile"), "w", encoding="utf-8") as f:
        f.write(render_caddyfile(clients))
    if clients:
        print("Configured clients:")
        for c in clients:
            print(f"  - {c['name']:<15} https://{c['domain']}")
    else:
        print("No clients yet. Add one with: ./add-client.sh <name> <domain>")


if __name__ == "__main__":
    main()
